In [ ]:
!pip3 install resampy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 35.2 MB/s eta 0:00:00


In [ ]:
import librosa
import librosa.core.audio
import librosa.display
import IPython.display as ipd
import os
import pandas as pd
import numpy as np

In [ ]:
audio_dataset_path = '/content/dataset/'
metadata = pd.read_csv('/content/dataset.csv')
metadata.head()

slice_file_name  type  start   end  classID     class
0    lovebird.mp3  .mp3    0.0  15.0        0  lovebird
1      KENARI.mp3  .mp3    0.0  15.0        1    kenari
2   lovebird2.mp3  .mp3    0.0  15.0        2  lovebird
3     KENARI1.mp3  .mp3    0.0  15.0        3    kenari
4   lovebird3.mp3  .mp3    0.0  15.0        4  lovebird

In [ ]:
file_name2 =metadata['slice_file_name']
print(file_name2)

0     lovebird.mp3
1       KENARI.mp3
2    lovebird2.mp3
3      KENARI1.mp3
4    lovebird3.mp3
5      KENARI2.mp3
6    lovebird4.mp3
7      KENARI3.mp3
8    lovebird5.mp3
9      KENARI4.mp3
Name: slice_file_name, dtype: object


In [ ]:
classification = metadata['class']
print(classification)

0    lovebird
1      kenari
2    lovebird
3      kenari
4    lovebird
5      kenari
6    lovebird
7      kenari
8    lovebird
9      kenari
Name: class, dtype: object


In [ ]:
def features_extractor(file_name):
  audio, sample_rate = librosa.load(file_name, res_type='kaiser_fast')
  mfccs_features = librosa.feature.mfcc(y=audio, sr=sample_rate, n_mfcc=60)
  mfccs_scaled_feature = np.mean(mfccs_features.T, axis=0)

  return mfccs_scaled_feature

In [ ]:
features = []
for index, row in metadata.iterrows():
    file_name = os.path.join(audio_dataset_path, row['slice_file_name'])
    class_label = row['class']
    data = features_extractor(file_name)
    features.append([data, class_label])

In [ ]:
data

array([-3.3016330e+02, -5.7321243e+01, -2.1067017e+01,  1.0772084e+02,
       -2.4626225e+01,  1.7834139e+01,  3.4539463e+01, -1.8385701e-01,
        1.2201544e+00,  1.5185383e+01,  4.3584013e+00,  1.3544942e+01,
       -1.6895918e+00,  5.8563337e+00, -2.5233836e+00,  7.2436838e+00,
       -1.5021615e+00,  5.0330563e+00, -3.6567748e+00,  5.2165875e+00,
       -3.4595506e+00,  5.4801126e+00, -4.5585966e+00,  1.1827490e+00,
       -4.0411601e+00,  4.5159297e+00, -6.8149772e+00,  2.8803153e+00,
       -4.0554862e+00,  1.2275000e+00, -5.3241906e+00, -7.5644232e-02,
       -6.9356900e-01, -3.2696128e+00, -3.2514887e+00, -2.0512085e-02,
       -1.6931875e+00, -3.7459068e+00, -8.7399948e-01, -3.5318456e+00,
       -1.4183531e+00, -1.4858661e+00, -3.3470068e+00, -2.4750805e+00,
       -2.6915534e+00, -1.6834329e+00, -3.2580006e+00, -1.4724402e+00,
       -3.7850339e+00, -1.1931354e+00, -2.9843721e+00, -1.4775352e+00,
       -1.8353440e+00, -1.6354698e+00, -1.8229859e+00, -1.4472116e+00,
      

In [ ]:
len(data)

60

In [ ]:
extracted_features_df = pd.DataFrame(features, columns=['feature', 'class'])
extracted_features_df.head()

feature     class
0  [-508.6843, -77.057556, -6.8986573, 54.943798,...  lovebird
1  [-321.11243, -65.88625, -15.215765, 99.57925, ...    kenari
2  [-489.8362, -92.072266, -5.578069, 67.44808, -...  lovebird
3  [-299.1487, -86.63422, -17.103996, 102.749306,...    kenari
4  [-497.7033, -97.776566, -18.241806, 59.095127,...  lovebird



1. **Membentuk Array Fitur (X)**:
   - Dalam kode ini, `features` adalah daftar yang berisi pasangan fitur dan kelas.
   - List comprehension `[item[0] for item in features]` digunakan untuk mengambil elemen pertama dari setiap pasangan fitur dan kelas dalam `features`.
   - Setiap elemen pertama dari setiap pasangan fitur dan kelas adalah fitur itu sendiri.
   - Kemudian, `np.array()` digunakan untuk mengonversi daftar fitur menjadi array numpy.
   - Jadi, `X` adalah array numpy yang berisi fitur-fitur dari data.

2. **Membentuk Array Kelas (y)**:
   - Dalam kode ini, lagi-lagi menggunakan list comprehension `[item[1] for item in features]` untuk mengambil elemen kedua dari setiap pasangan fitur dan kelas dalam `features`.
   - Setiap elemen kedua dari setiap pasangan fitur dan kelas adalah kelas atau label.
   - Kemudian, `np.array()` digunakan untuk mengonversi daftar label menjadi array numpy.
   - Jadi, `y` adalah array numpy yang berisi kelas atau label dari data.



In [ ]:
X = np.array([item[0] for item in features])
y = np.array([item[1] for item in features])

In [ ]:
X

array([[-5.08684296e+02, -7.70575562e+01, -6.89865732e+00,
         5.49437981e+01, -1.01068277e+01,  1.21979218e+01,
         3.23088837e+00,  1.29152422e+01,  5.53084993e+00,
         7.68839264e+00, -2.55554461e+00,  1.00712099e+01,
        -2.26351070e+00,  6.46572781e+00, -2.68775296e+00,
         3.81897259e+00, -2.78914785e+00,  4.49493742e+00,
        -3.42097926e+00,  3.48087621e+00, -1.41576445e+00,
         1.89246368e+00, -1.45840192e+00,  3.40108180e+00,
         4.93593723e-01,  1.34297037e+00,  8.56273711e-01,
         3.64762902e+00,  1.53639507e+00,  3.62742209e+00,
         4.86082882e-02,  4.96929741e+00,  1.12298810e+00,
         3.35280085e+00,  2.05503345e+00,  2.70765948e+00,
         2.22584891e+00,  2.71116638e+00,  5.35507023e-01,
         2.38735342e+00,  1.42433321e+00,  1.35111034e+00,
         2.54491955e-01,  1.87563598e+00,  2.16294706e-01,
         7.01818585e-01,  6.65569901e-01,  5.27676642e-01,
        -8.23796988e-02,  9.00764287e-01, -7.63288677e-0

In [ ]:
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
y = to_categorical(labelencoder.fit_transform(y))

In [ ]:
y

array([[0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.]], dtype=float32)

In [ ]:
from sklearn.model_selection import train_test_split

# Membagi data menjadi set pelatihan dan pengujian
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=0)


In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten
from tensorflow.keras.optimizers import Adam
from sklearn import metrics

In [ ]:
model =Sequential()
model.add(Dense(len(X_train[0]),
                activation='relu', input_shape=X_train[0].shape))
model.add(Dense(len(X_train[0, :]), activation='relu'))
model.add(Dense(len(X_train[0, :]), activation='tanh'))
model.add(Dense(len(y_train[0, :]), activation='sigmoid'))


In [ ]:
# Compile model
model.compile(optimizer='adam',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

# Tampilkan ringkasan model
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_7 (Dense)             (None, 60)                3660      
                                                                 
 dense_8 (Dense)             (None, 60)                3660      
                                                                 
 dense_9 (Dense)             (None, 60)                3660      
                                                                 
 dense_10 (Dense)            (None, 2)                 122       
                                                                 
Total params: 11102 (43.37 KB)
Trainable params: 11102 (43.37 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
from tensorflow.keras.callbacks import ModelCheckpoint
from datetime import datetime

num_epochs = 15
num_batch = 32

checkpointer = ModelCheckpoint(filepath='saved_models/voicerecog.h5',
                               verbose=1, save_best_only=True)
start = datetime.now()
history = model.fit(X_train, y_train, validation_data=(
    X_test, y_test), callbacks=[checkpointer], epochs=num_epochs, batch_size=num_batch)

duration = datetime.now() - start
print('Training completed in time: ', duration)

# Print accuracy
train_accuracy = history.history['accuracy'][-1] * 100
test_accuracy = history.history['val_accuracy'][-1] * 100
print('Train Accuracy: {:.2f}%'.format(train_accuracy))
print('Test Accuracy: {:.2f}%'.format(test_accuracy))


Epoch 1/15
1/1 [==============================] - ETA: 0s - loss: 0.3407 - accuracy: 0.6667
Epoch 1: val_loss improved from inf to 1.01189, saving model to saved_models/voicerecog.h5
1/1 [==============================] - 0s 101ms/step - loss: 0.3407 - accuracy: 0.6667 - val_loss: 1.0119 - val_accuracy: 0.2500
Epoch 2/15
1/1 [==============================] - ETA: 0s - loss: 0.3317 - accuracy: 0.6667
Epoch 2: val_loss improved from 1.01189 to 0.89734, saving model to saved_models/voicerecog.h5
1/1 [==============================] - 0s 58ms/step - loss: 0.3317 - accuracy: 0.6667 - val_loss: 0.8973 - val_accuracy: 0.2500
Epoch 3/15
1/1 [==============================] - ETA: 0s - loss: 0.3058 - accuracy: 0.6667
Epoch 3: val_loss improved from 0.89734 to 0.83636, saving model to saved_models/voicerecog.h5
1/1 [==============================] - 0s 59ms/step - loss: 0.3058 - accuracy: 0.6667 - val_loss: 0.8364 - val_accuracy: 0.2500
Epoch 4/15
1/1 [==============================] - ETA: 0s 

In [ ]:
prediction_label = model.predict(X_test)
print(prediction_label)

1/1 [==============================] - 0s 66ms/step
[[0.5787744  0.7749115 ]
 [0.68122035 0.37958133]
 [0.5106333  0.74086124]
 [0.6375252  0.31596062]]


In [ ]:
import numpy as np

# Contoh output model Anda
output = np.array([[0.5787744, 0.7749115],
 [0.68122035, 0.37958133],
 [0.5106333, 0.74086124],
 [0.6375252, 0.31596062]])

# Mendapatkan indeks kelas dengan probabilitas tertinggi untuk setiap sampel
predicted_classes = np.argmax(output, axis=1)

print("Kelas yang diprediksi untuk setiap sampel:", predicted_classes)


Kelas yang diprediksi untuk setiap sampel: [1 0 1 0]
